agent: charliepai2g48h5-frieren
batch_size: 4
debug: false
epochs: 70
experiment_name: charliepai2g48h5-frieren/mlp-ratio15
lr: 0.00015
model_config:
  fun_dim: 22
  mlp_ratio: 1.5
  n_head: 2
  n_hidden: 96
  n_layers: 4
  out_dim: 3
  output_dims:
  - 1
  - 1
  - 1
  output_fields:
  - Ux
  - Uy
  - p
  slice_num: 24
  space_dim: 2
n_params: 294167
skip_test: false
splits_dir: /mnt/new-pvc/datasets/tandemfoil/splits_v2
surf_weight: 10.0
train_samples: 1499
val_samples:
  val_geom_camber_cruise: 100
  val_geom_camber_rc: 100
  val_re_rand: 100
  val_single_in_dist: 100
weight_decay: 0.0003
